---
kind: pipeline
type: docker
name: commit

steps:
  - name: do nothing
    image: alpine:3.15
    commands:
      - echo "You can now promote different targets manually"

trigger:
  event:
    exclude:
      - promote

---
kind: pipeline
type: docker
name: mod-plugin-builder amd64

platform:
  os: linux
  arch: amd64

concurrency:
  limit: 1

clone:
  disable: true

steps:
  - name: clone
    image: alpine/git
    commands:
      - git clone --depth 1 https://github.com/moddevices/mod-plugin-builder .

  - name: build
    image: plugins/docker
    settings:
      repo: cbix/mod-plugin-builder
      username: cbix
      password:
        from_secret: docker-pass
      dockerfile: docker/Dockerfile
      build_args:
        - platform=${platform:-moddwarf}
      tags: ${platform:-moddwarf}-amd64

trigger:
  event:
    - promote
  target:
    - mod-plugin-builder

---
kind: pipeline
type: docker
name: mod-plugin-builder arm64

platform:
  os: linux
  arch: arm64

concurrency:
  limit: 1

clone:
  disable: true

steps:
  - name: clone
    image: alpine/git
    commands:
      - git clone --depth 1 https://github.com/moddevices/mod-plugin-builder .

  - name: build
    image: plugins/docker
    settings:
      repo: cbix/mod-plugin-builder
      username: cbix
      password:
        from_secret: docker-pass
      dockerfile: docker/Dockerfile
      build_args:
        - platform=${platform:-moddwarf}
      tags: ${platform:-moddwarf}-arm64

trigger:
  event:
    - promote
  target:
    - mod-plugin-builder

---
kind: pipeline
type: docker
name: mod-plugin-builder manifest

clone:
  disable: true

steps:
  - name: push
    image: plugins/manifest
    settings:
      username: cbix
      password:
        from_secret: docker-pass
      target: cbix/mod-plugin-builder:${platform:-moddwarf}
      template: cbix/mod-plugin-builder:${platform:-moddwarf}-ARCH
      platforms:
        - linux/amd64
        - linux/arm64
      ignore_missing: true

depends_on:
  - mod-plugin-builder amd64
  - mod-plugin-builder arm64

trigger:
  event:
    - promote
  target:
    - mod-plugin-builder

---
kind: pipeline
type: docker
name: Update amd64 images

clone:
  disable: true

platform:
  os: linux
  arch: amd64

steps:
  - name: Update archlinux image
    image: archlinux/archlinux:base-devel
    pull: always
    commands:
      - echo Image updated

trigger:
  event:
    - cron

---
kind: pipeline
type: docker
name: Update arm64 images

clone:
  disable: true

platform:
  os: linux
  arch: arm64

steps:
  - name: Update archlinux image
    image: lopsided/archlinux-arm64v8:devel
    pull: always
    commands:
      - echo Image updated

trigger:
  event:
    - cron

---
kind: pipeline
type: docker
name: Test rollback

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
  - name: print info
    image: archlinux/archlinux:base-devel
    commands:
      - env

trigger:
  event:
    - rollback
